# Generated by Django 4.1.1 on 2022-09-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toparlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('oynalan_oyun', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulma', models.IntegerField()),
                ('utuk', models.IntegerField()),
                ('gechirlen_gol', models.IntegerField()),
                ('ozune_gool', models.IntegerField()),
                ('gol_ara', models.IntegerField()),
            ],
            options={
                'ordering': ['utuk'],
            },
        ),
        migrations.CreateModel(
            name='topar_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.ImageField(upload_to='pics')),
                ('logo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.toparlar')),
            ],
        ),
    ]
