# Generated by Django 4.1.1 on 2022-09-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='topar_logo',
        ),
        migrations.DeleteModel(
            name='toparlar',
        ),
    ]
