# Generated by Django 4.1.1 on 2022-09-23 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turkmenfutbol', '0002_delete_topar_logo_delete_toparlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_dashky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('place', models.CharField(max_length=75)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='about_icherki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_hakda', models.TextField()),
                ('kada', models.TextField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='apl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='apl_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='bundes_liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='bundes_liga_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='CL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='CL_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='football_news_continue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkm', models.BooleanField(default=False)),
                ('apl', models.BooleanField(default=False)),
                ('cl', models.BooleanField(default=False)),
                ('news_pics', models.ImageField(upload_to='news_pictures')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('saylanan', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='habarlashmak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='importand_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_pics', models.ImageField(upload_to='news_pictures')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='laliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='laliga_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='league1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='league1_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='league_logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='league_logos')),
            ],
        ),
        migrations.CreateModel(
            name='seria_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='seria_a_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='tkm_league',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='tkm_league_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(default='asas', max_length=100)),
                ('video', models.FileField(upload_to='videos')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='topar_surat_tkm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='tkm_league_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.tkm_league')),
            ],
        ),
        migrations.CreateModel(
            name='topar_surat_seria_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='seria_a_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.seria_a')),
            ],
        ),
        migrations.CreateModel(
            name='topar_surat_league1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='league1_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.league1')),
            ],
        ),
        migrations.CreateModel(
            name='topar_surat_laliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='laliga_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.laliga')),
            ],
        ),
        migrations.CreateModel(
            name='topar_surat_CL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='CL_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.cl')),
            ],
        ),
        migrations.CreateModel(
            name='topar_surat_bundes_liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bundes_liga_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.bundes_liga')),
            ],
        ),
        migrations.CreateModel(
            name='topar_surat_apl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='apl_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.apl')),
            ],
        ),
    ]
