# Generated by Django 4.1.1 on 2022-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apl',
            name='g1',
            field=models.BooleanField(default=True),
        ),
    ]
