# Generated by Django 4.1.1 on 2022-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0004_apl_g1'),
    ]

    operations = [
        migrations.AddField(
            model_name='apl',
            name='g2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apl',
            name='g3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apl',
            name='g4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apl',
            name='g5',
            field=models.BooleanField(default=True),
        ),
    ]
