# Generated by Django 4.1.1 on 2022-09-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0006_last5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl5',
            fields=[
                ('netije', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='turkmenfutbol.last5')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.cl')),
            ],
        ),
    ]
