# Generated by Django 4.1.1 on 2022-09-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0007_cl5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last5',
            name='draw',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='last5',
            name='lose',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='last5',
            name='win',
            field=models.CharField(max_length=10),
        ),
    ]
