# Generated by Django 4.1.1 on 2022-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0008_alter_last5_draw_alter_last5_lose_alter_last5_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last5',
            name='draw',
            field=models.ImageField(upload_to='last5'),
        ),
        migrations.AlterField(
            model_name='last5',
            name='lose',
            field=models.ImageField(upload_to='last5'),
        ),
        migrations.AlterField(
            model_name='last5',
            name='win',
            field=models.ImageField(upload_to='last5'),
        ),
    ]
