# Generated by Django 4.1.1 on 2022-09-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0011_cl5_salam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl5',
            old_name='property',
            new_name='property2',
        ),
    ]
