# Generated by Django 4.1.1 on 2022-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0020_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='jem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.CharField(max_length=10)),
                ('lose', models.CharField(max_length=10)),
            ],
        ),
    ]
