# Generated by Django 4.1.1 on 2022-09-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0021_jem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl',
            name='id',
        ),
        migrations.AddField(
            model_name='cl',
            name='belli',
            field=models.OneToOneField(default=23, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='turkmenfutbol.jem'),
        ),
    ]
