# Generated by Django 4.1.1 on 2022-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0022_remove_cl_id_cl_belli'),
    ]

    operations = [
        migrations.AddField(
            model_name='jem',
            name='draw',
            field=models.CharField(default='draw', max_length=10),
            preserve_default=False,
        ),
    ]
