# Generated by Django 4.1.1 on 2022-09-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0023_jem_draw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jem',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='jem',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='jem',
            name='win',
        ),
        migrations.AddField(
            model_name='jem',
            name='wow',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='cl',
            name='belli',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='turkmenfutbol.jem'),
        ),
    ]
