# Generated by Django 4.1.1 on 2022-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0024_remove_jem_draw_remove_jem_lose_remove_jem_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl',
            name='ikinji',
            field=models.OneToOneField(default='win', on_delete=django.db.models.deletion.CASCADE, related_name='salam', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
    ]
