# Generated by Django 4.1.1 on 2022-09-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0025_cl_ikinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl',
            name='ikinji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ikinji', to='turkmenfutbol.jem'),
        ),
    ]
