# Generated by Django 4.1.1 on 2022-09-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0027_cl_bashinji_cl_dordunji_cl_uchunji_alter_cl_ikinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl',
            name='bashinji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bashinji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='dordunji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dordunji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='ikinji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ikinji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='uchunji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uchunji', to='turkmenfutbol.jem'),
        ),
    ]
