# Generated by Django 4.1.1 on 2022-09-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0030_alter_cl_birinji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apl',
            name='g1',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='g2',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='g3',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='g4',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='g5',
        ),
    ]
