# Generated by Django 4.1.1 on 2022-09-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0031_remove_apl_g1_remove_apl_g2_remove_apl_g3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl',
            name='bashinji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='birinji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='dordunji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='ikinji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='uchunji',
        ),
    ]
