# Generated by Django 4.1.1 on 2022-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0032_remove_cl_bashinji_remove_cl_birinji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jem',
            name='wow',
            field=models.CharField(max_length=10),
        ),
    ]
