# Generated by Django 4.1.1 on 2022-09-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0033_alter_jem_wow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl',
            name='bashinji',
            field=models.OneToOneField(default='bashinji', on_delete=django.db.models.deletion.CASCADE, related_name='bashinji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='birinji',
            field=models.OneToOneField(default='birinji', on_delete=django.db.models.deletion.CASCADE, related_name='birinji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='dordunji',
            field=models.OneToOneField(default='dordunji', on_delete=django.db.models.deletion.CASCADE, related_name='dordunji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='ikinji',
            field=models.OneToOneField(default='ikinji', on_delete=django.db.models.deletion.CASCADE, related_name='ikinji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='uchunji',
            field=models.OneToOneField(default='uchunji', on_delete=django.db.models.deletion.CASCADE, related_name='uchunji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
    ]
