# Generated by Django 4.1.1 on 2022-09-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0034_cl_bashinji_cl_birinji_cl_dordunji_cl_ikinji_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl',
            name='bashinji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='birinji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='dordunji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='ikinji',
        ),
        migrations.RemoveField(
            model_name='cl',
            name='uchunji',
        ),
    ]
