# Generated by Django 4.1.1 on 2022-09-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0035_remove_cl_bashinji_remove_cl_birinji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl',
            name='bashinji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bashinji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='birinji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='birinji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='dordunji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='dordunji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='ikinji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ikinji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cl',
            name='uchunji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='uchunji', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
    ]
