# Generated by Django 4.1.1 on 2022-09-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0036_cl_bashinji_cl_birinji_cl_dordunji_cl_ikinji_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topar_surat_cl',
            name='property',
        ),
        migrations.DeleteModel(
            name='CL',
        ),
        migrations.DeleteModel(
            name='topar_surat_CL',
        ),
    ]
