# Generated by Django 4.1.1 on 2022-09-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0037_remove_topar_surat_cl_property_delete_cl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='CL_logos')),
                ('utuk', models.IntegerField(default=1)),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
                ('bashinji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bashinji', to='turkmenfutbol.jem')),
                ('birinji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birinji', to='turkmenfutbol.jem')),
                ('dordunji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dordunji', to='turkmenfutbol.jem')),
                ('ikinji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ikinji', to='turkmenfutbol.jem')),
                ('uchunji', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uchunji', to='turkmenfutbol.jem')),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='topar_surat_CL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='CL_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.cl')),
            ],
        ),
    ]
