# Generated by Django 4.1.1 on 2022-09-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0038_cl_topar_surat_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topar_surat_laliga',
            name='property',
        ),
        migrations.DeleteModel(
            name='laliga',
        ),
        migrations.DeleteModel(
            name='topar_surat_laliga',
        ),
    ]
