# Generated by Django 4.1.1 on 2022-09-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0040_laliga_topar_surat_laliga'),
    ]

    operations = [
        migrations.AddField(
            model_name='laliga',
            name='birinji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
    ]
