# Generated by Django 4.1.1 on 2022-09-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0043_laliga_uchunji'),
    ]

    operations = [
        migrations.AddField(
            model_name='laliga',
            name='bashinji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bashinji2', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laliga',
            name='dordunji',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='dordunji2', to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
    ]
