# Generated by Django 4.1.1 on 2022-09-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0046_remove_apl_birinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laliga',
            name='birinji',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birinji2', to='turkmenfutbol.jem'),
        ),
    ]
