# Generated by Django 4.1.1 on 2022-09-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0049_remove_apl_birinji'),
    ]

    operations = [
        migrations.AddField(
            model_name='apl',
            name='birinji',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='turkmenfutbol.jem'),
            preserve_default=False,
        ),
    ]
