# Generated by Django 4.1.1 on 2022-09-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0058_apl_birinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apl',
            name='birinji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.jem'),
        ),
    ]
