# Generated by Django 4.1.1 on 2022-09-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0060_apl_ikinji'),
    ]

    operations = [
        migrations.AddField(
            model_name='apl',
            name='uchunji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to='turkmenfutbol.jem'),
        ),
    ]
