# Generated by Django 4.1.1 on 2022-09-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0065_alter_laliga_birinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laliga',
            name='ikinji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e', to='turkmenfutbol.jem'),
        ),
    ]
