# Generated by Django 4.1.1 on 2022-09-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0066_alter_laliga_ikinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laliga',
            name='bashinji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='dordunji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='uchunji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f', to='turkmenfutbol.jem'),
        ),
    ]
