# Generated by Django 4.1.1 on 2022-09-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0067_alter_laliga_bashinji_alter_laliga_dordunji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laliga',
            name='bashinji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bashinji2', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='birinji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birinji2', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='dordunji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dordunji2', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='ikinji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ikinji2', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='uchunji',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uchunji2', to='turkmenfutbol.jem'),
        ),
    ]
