# Generated by Django 4.1.1 on 2022-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0072_remove_apl_birinji_apl_birinji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apl',
            name='birinji',
            field=models.ManyToManyField(related_name='z', to='turkmenfutbol.jem'),
        ),
    ]
