# Generated by Django 4.1.1 on 2022-09-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0073_alter_apl_birinji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apl',
            name='birinji',
        ),
        migrations.AddField(
            model_name='apl',
            name='birinji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.jem'),
        ),
    ]
