# Generated by Django 4.1.1 on 2022-09-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0076_alter_apl_bashinji_alter_apl_dordunji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl',
            name='bashinji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bashinji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='birinji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birinji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='dordunji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dordunji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='ikinji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikinji', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='cl',
            name='uchunji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uchunji', to='turkmenfutbol.jem'),
        ),
    ]
