# Generated by Django 4.1.1 on 2022-09-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0080_alter_bundes_liga_bashinji_alter_bundes_liga_birinji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league1',
            name='bashinji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='league1',
            name='birinji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='league1',
            name='dordunji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='league1',
            name='ikinji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m', to='turkmenfutbol.jem'),
        ),
        migrations.AlterField(
            model_name='league1',
            name='uchunji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n', to='turkmenfutbol.jem'),
        ),
    ]
