# Generated by Django 4.1.1 on 2022-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0081_alter_league1_bashinji_alter_league1_birinji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jem',
            old_name='wow',
            new_name='win',
        ),
        migrations.AddField(
            model_name='jem',
            name='draw',
            field=models.CharField(default='draw', max_length=10),
        ),
        migrations.AddField(
            model_name='jem',
            name='lose',
            field=models.CharField(default='lose', max_length=10),
        ),
    ]
