# Generated by Django 4.1.1 on 2022-09-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0082_rename_wow_jem_win_jem_draw_jem_lose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jem',
            name='draw',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jem',
            name='lose',
            field=models.CharField(max_length=10),
        ),
    ]
