# Generated by Django 4.1.1 on 2022-09-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0083_alter_jem_draw_alter_jem_lose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jem',
            old_name='draw',
            new_name='wow',
        ),
        migrations.RemoveField(
            model_name='jem',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='jem',
            name='win',
        ),
    ]
