# Generated by Django 4.1.1 on 2022-09-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0084_rename_draw_jem_wow_remove_jem_lose_remove_jem_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apl',
            name='bashinji',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='birinji',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='dordunji',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='ikinji',
        ),
        migrations.RemoveField(
            model_name='apl',
            name='uchunji',
        ),
    ]
