# Generated by Django 4.1.1 on 2022-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0086_remove_bundes_liga_bashinji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wow', models.CharField(max_length=10)),
            ],
        ),
    ]
