# Generated by Django 4.1.1 on 2022-09-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0087_jem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jem',
        ),
    ]
