# Generated by Django 4.1.1 on 2022-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0088_delete_jem'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiwi', models.CharField(max_length=5)),
            ],
        ),
    ]
