# Generated by Django 4.1.1 on 2022-09-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0089_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='apl',
            name='maglumat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='turkmenfutbol.subcategory'),
        ),
    ]
