# Generated by Django 4.1.1 on 2022-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0091_remove_apl_maglumat_apl_maglumat1_apl_maglumat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='wiwi',
            field=models.IntegerField(),
        ),
    ]
