# Generated by Django 4.1.1 on 2022-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0092_alter_subcategory_wiwi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='wiwi',
            field=models.CharField(max_length=5),
        ),
    ]
