# Generated by Django 4.1.1 on 2022-09-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0094_alter_apl_maglumat1_alter_apl_maglumat2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='last5',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='last5',
            name='lose',
        ),
    ]
