# Generated by Django 4.1.1 on 2022-09-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0099_importand_slide_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importand_slide',
            name='when',
        ),
    ]
