# Generated by Django 4.1.1 on 2022-09-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0100_remove_importand_slide_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='football_news_continue',
            name='when',
            field=models.IntegerField(default=1),
        ),
    ]
