# Generated by Django 4.1.1 on 2022-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0101_football_news_continue_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='Images_of_videos'),
        ),
    ]
