# Generated by Django 4.1.1 on 2022-09-30 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0103_alter_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_logos',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
