# Generated by Django 4.1.1 on 2022-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0104_league_logos_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='football_news_continue',
            name='months',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
