# Generated by Django 4.1.1 on 2022-10-03 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0105_football_news_continue_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Each_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.group_name')),
            ],
        ),
        migrations.AddField(
            model_name='cl',
            name='related',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.each_group'),
        ),
    ]
