# Generated by Django 4.1.1 on 2022-10-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0107_alter_cl_related'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CL',
            new_name='CL_club',
        ),
    ]
