# Generated by Django 4.1.1 on 2022-10-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0108_rename_cl_cl_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topar_surat_cl',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.each_group'),
        ),
    ]
