# Generated by Django 4.1.1 on 2022-10-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0110_cl_images_rename_each_group_each_cl_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_club',
            name='maglumat1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='y', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='cl_club',
            name='maglumat2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='u', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='cl_club',
            name='maglumat3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='i', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='cl_club',
            name='maglumat4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='o', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='cl_club',
            name='maglumat5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p', to='turkmenfutbol.subcategory'),
        ),
    ]
