# Generated by Django 4.1.1 on 2022-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0111_cl_club_maglumat1_cl_club_maglumat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_name',
            name='group_name',
            field=models.CharField(max_length=7),
        ),
    ]
