# Generated by Django 4.1.1 on 2022-10-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0112_alter_group_name_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='football_news_continue',
            name='bundes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='football_news_continue',
            name='global_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='football_news_continue',
            name='laliga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='football_news_continue',
            name='liga_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='football_news_continue',
            name='seria_1',
            field=models.BooleanField(default=False),
        ),
    ]
