# Generated by Django 4.1.1 on 2022-10-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0113_football_news_continue_bundes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='football_news_continue',
            old_name='seria_1',
            new_name='seria_a',
        ),
    ]
