# Generated by Django 4.1.1 on 2022-10-04 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0114_rename_seria_1_football_news_continue_seria_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkm_league',
            name='maglumat1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='tkm_league',
            name='maglumat2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='s', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='tkm_league',
            name='maglumat3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='d', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='tkm_league',
            name='maglumat4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='f', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='tkm_league',
            name='maglumat5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='g', to='turkmenfutbol.subcategory'),
        ),
    ]
