# Generated by Django 4.1.1 on 2022-10-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0116_laliga_maglumat1_laliga_maglumat2_laliga_maglumat3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seria_a',
            name='maglumat1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='x', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='seria_a',
            name='maglumat2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='c', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='seria_a',
            name='maglumat3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='v', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='seria_a',
            name='maglumat4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to='turkmenfutbol.subcategory'),
        ),
        migrations.AddField(
            model_name='seria_a',
            name='maglumat5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='n', to='turkmenfutbol.subcategory'),
        ),
    ]
