# Generated by Django 4.1.1 on 2022-10-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0118_bundes_liga_maglumat1_bundes_liga_maglumat2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_icherki',
        ),
    ]
