# Generated by Django 4.1.1 on 2022-10-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0119_delete_about_icherki'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferLiga_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='ConferLiga_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='EL_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='EL_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='EL_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='EL_logos')),
                ('utuk', models.IntegerField()),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
                ('maglumat1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mm', to='turkmenfutbol.subcategory')),
                ('maglumat2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nn', to='turkmenfutbol.subcategory')),
                ('maglumat3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bb', to='turkmenfutbol.subcategory')),
                ('maglumat4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vv', to='turkmenfutbol.subcategory')),
                ('maglumat5', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cc', to='turkmenfutbol.subcategory')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.each_cl_group')),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
        migrations.CreateModel(
            name='ConferLiga_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='ConferLiga_logos')),
                ('utuk', models.IntegerField()),
                ('oyun_jem', models.IntegerField()),
                ('utush', models.IntegerField()),
                ('dene_den', models.IntegerField()),
                ('utulush', models.IntegerField()),
                ('salnan_gol', models.IntegerField()),
                ('ozune_gol', models.IntegerField()),
                ('aratapawut', models.IntegerField()),
                ('maglumat1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xx', to='turkmenfutbol.subcategory')),
                ('maglumat2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zz', to='turkmenfutbol.subcategory')),
                ('maglumat3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ll', to='turkmenfutbol.subcategory')),
                ('maglumat4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kk', to='turkmenfutbol.subcategory')),
                ('maglumat5', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jj', to='turkmenfutbol.subcategory')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.each_cl_group')),
            ],
            options={
                'ordering': ['-utuk', '-aratapawut', '-salnan_gol', '-utush'],
            },
        ),
    ]
