# Generated by Django 4.1.1 on 2022-10-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0120_conferliga_images_el_images_el_club_conferliga_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Each_EL_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.group_name')),
            ],
        ),
        migrations.CreateModel(
            name='Each_ConferLiga_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.group_name')),
            ],
        ),
        migrations.AlterField(
            model_name='conferliga_club',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.each_conferliga_group'),
        ),
        migrations.AlterField(
            model_name='el_club',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.each_el_group'),
        ),
    ]
