# Generated by Django 4.1.1 on 2022-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0122_league_logos_gysga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_logos',
            name='gysga',
            field=models.CharField(max_length=20),
        ),
    ]
