# Generated by Django 4.1.1 on 2022-10-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0124_football_news_continue_conf_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='football_news_continue',
            name='apl',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='bundes',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='conf_l',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='el',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='global_news',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='laliga',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='liga_1',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='seria_a',
        ),
        migrations.RemoveField(
            model_name='football_news_continue',
            name='tkm',
        ),
    ]
