# Generated by Django 4.1.1 on 2022-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0125_remove_football_news_continue_apl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolumler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habar_lig', models.CharField(default=1, max_length=10)),
            ],
        ),
    ]
