# Generated by Django 4.1.1 on 2022-10-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenfutbol', '0126_bolumler'),
    ]

    operations = [
        migrations.AddField(
            model_name='football_news_continue',
            name='bolum_sayla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turkmenfutbol.bolumler'),
        ),
    ]
